services:
  nginx:
    image: local-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - nginx-network

  python-app:
    image: local-python-app
    container_name: python_app
    expose:
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge





     # Replace eighty with 80 in ports.
#Remove the unsupported options field in networks.
#Correct expose to "8000" for python-app.
  #compelex->complex
#bridg->bridge